// 03/tsx-examples/src/App.vue
<script setup>
import Expander from './components/Expander.vue';
import ListItems from './components/ListItems.vue';
import CheckboxItem from './components/CheckboxItemVue/index.vue';
import ExpanderVShow from './components/ExpanderVShow.vue';

const listItems = ['item1', 'item2', 'item3'];
</script>

<template>
  <h1>.vue based</h1>
  <Expander />
  <ListItems :listItems="listItems" />
  <CheckboxItem />
  <ExpanderVShow />
</template>

// 03/tsx-examples/src/App.tsx
import { CheckboxItem } from './components/CheckboxItemTsx/index';
import { Expander } from './components/Expander';
import { ExpanderVShow } from './components/ExpanderVShow';
import { ListItems } from './components/ListItems';

const listItems = ['item1', 'item2', 'item3'];

export default () => {
  return (
    <>
      <h1>.tsx based</h1>
      <Expander />
      <ListItems listItems={listItems} />
      <CheckboxItem />
      <ExpanderVShow />
    </>
  );
};
